package com.beryndil.pharos.data.regimen

import androidx.room.testing.MigrationTestHelper
import androidx.test.platform.app.InstrumentationRegistry
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Rule
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.RobolectricTestRunner

/**
 * Migration test harness for [RegimenDatabase] (spec §3.5, Standards §5).
 *
 * At schema v1, there are no migrations to test. The harness validates that:
 * 1. The exported schema JSON was generated by KSP before tests run.
 * 2. [MigrationTestHelper.createDatabase] can create a v1 database from the schema JSON.
 * 3. All required tables exist in the v1 schema.
 *
 * When v2 is added (any future slice that adds/modifies a column), add a
 * testMigrateV1ToV2() test here with the corresponding migration SQL.
 *
 * Schema assets exposed to Robolectric via:
 *   sourceSets { named("test") { assets.srcDir("$projectDir/schemas") } }
 */
@RunWith(RobolectricTestRunner::class)
class MigrationHarnessTest {

    @get:Rule
    val migrationHelper: MigrationTestHelper = MigrationTestHelper(
        InstrumentationRegistry.getInstrumentation(),
        RegimenDatabase::class.java,
    )

    @Test
    fun createV1SchemaAndVerifyAllTables() {
        val db = migrationHelper.createDatabase(RegimenDatabaseFactory.DATABASE_NAME, 1)
        db.use {
            val tables = mutableSetOf<String>()
            db.query(
                "SELECT name FROM sqlite_master WHERE type='table'",
                emptyArray<Any?>(),
            ).use { cursor ->
                while (cursor.moveToNext()) tables.add(cursor.getString(0))
            }
            val requiredTables = listOf(
                "medications",
                "schedules",
                "schedule_phases",
                "dose_instances",
                "refill_records",
                "settings",
            )
            for (table in requiredTables) {
                assertTrue("Table '$table' must exist in v1 schema", tables.contains(table))
            }
        }
    }

    /** dose_instances must be queryable on an empty v1 database. */
    @Test
    fun v1DoseInstancesTableIsQueryable() {
        val db = migrationHelper.createDatabase(RegimenDatabaseFactory.DATABASE_NAME, 1)
        db.use {
            db.query(
                "SELECT id, state FROM dose_instances WHERE state='SCHEDULED'",
                emptyArray<Any?>(),
            ).use { cursor ->
                assertTrue(
                    "Query on empty dose_instances must return 0 rows",
                    !cursor.moveToFirst(),
                )
            }
        }
    }

    /**
     * v1 → v2 (Slice 5): the append-only [dose_transitions] table is created without touching
     * existing data. A row inserted at v1 must survive the migration (Standards §5: never a
     * destructive migration on a path users reach).
     */
    @Test
    fun migrateV1ToV2_addsDoseTransitionsTable_preservingData() {
        migrationHelper.createDatabase(RegimenDatabaseFactory.DATABASE_NAME, 1).use { v1 ->
            v1.execSQL(
                "INSERT INTO medications (id, name, rxcui, ingredientsJson, strength, form, " +
                    "doseAmount, prescriber, pharmacy, purpose, isFreeText, status, startEpochMs, " +
                    "endEpochMs, createdAtEpochMs, updatedAtEpochMs) VALUES " +
                    "('m1','Metoprolol',NULL,'[]','25 mg','TABLET','1 tablet',NULL,NULL,NULL,0," +
                    "'ACTIVE',0,NULL,0,0)",
            )
        }

        val v2 = migrationHelper.runMigrationsAndValidate(
            RegimenDatabaseFactory.DATABASE_NAME,
            2,
            true,
            RegimenDatabaseFactory.MIGRATION_1_2,
        )
        v2.use {
            // The pre-existing medication row survived the migration.
            v2.query("SELECT COUNT(*) FROM medications", emptyArray<Any?>()).use { c ->
                assertTrue(c.moveToFirst())
                assertEquals(1, c.getInt(0))
            }
            // The new append-only table exists and is queryable.
            v2.query("SELECT COUNT(*) FROM dose_transitions", emptyArray<Any?>()).use { c ->
                assertTrue(c.moveToFirst())
                assertEquals(0, c.getInt(0))
            }
        }
    }

    /**
     * v2 → v3 (A1 Critical Alerts): [isCritical] column is added to medications with DEFAULT 0.
     * Existing rows must survive the migration with isCritical=0 (non-critical by default,
     * Standards §5: never destructive, Law 4: no silent opt-in to critical behavior).
     */
    @Test
    fun migrateV2ToV3_addIsCriticalColumn_existingRowsDefaultToFalse() {
        // Seed a v2 database with one medication row.
        migrationHelper.createDatabase(RegimenDatabaseFactory.DATABASE_NAME, 2).use { v2 ->
            v2.execSQL(
                "INSERT INTO medications (id, name, rxcui, ingredientsJson, strength, form, " +
                    "doseAmount, prescriber, pharmacy, purpose, isFreeText, status, startEpochMs, " +
                    "endEpochMs, createdAtEpochMs, updatedAtEpochMs) VALUES " +
                    "('m2','Lisinopril',NULL,'[]','10 mg','TABLET','1 tablet',NULL,NULL,NULL,0," +
                    "'ACTIVE',0,NULL,0,0)",
            )
        }

        // Apply MIGRATION_2_3 and validate the resulting schema matches Room's expectation.
        val v3 = migrationHelper.runMigrationsAndValidate(
            RegimenDatabaseFactory.DATABASE_NAME,
            3,
            true,
            RegimenDatabaseFactory.MIGRATION_2_3,
        )
        v3.use {
            // Pre-existing medication row survived.
            v3.query("SELECT COUNT(*) FROM medications", emptyArray<Any?>()).use { c ->
                assertTrue(c.moveToFirst())
                assertEquals(1, c.getInt(0))
            }
            // isCritical column exists and defaults to 0 (false) for all pre-existing rows.
            v3.query(
                "SELECT isCritical FROM medications WHERE id = 'm2'",
                emptyArray<Any?>(),
            ).use { c ->
                assertTrue("Row must still exist after migration", c.moveToFirst())
                assertEquals(
                    "isCritical must default to 0 for pre-existing rows (Law 4 — no silent opt-in)",
                    0,
                    c.getInt(0),
                )
            }
        }
    }

    /**
     * v3 → v4 (G1 Per-medication miss window): [missWindowMinutes] column is added to medications
     * with DEFAULT 60. Existing rows must survive the migration with missWindowMinutes=60, matching
     * the prior hardcoded behavior (Standards §5: no behavioral change for existing users).
     */
    @Test
    fun migrateV3ToV4_addMissWindowMinutesColumn_existingRowsDefaultTo60() {
        // Seed a v3 database with one medication row (no isCritical col needed — it was added v2→v3).
        migrationHelper.createDatabase(RegimenDatabaseFactory.DATABASE_NAME, 3).use { v3 ->
            v3.execSQL(
                "INSERT INTO medications (id, name, rxcui, ingredientsJson, strength, form, " +
                    "doseAmount, prescriber, pharmacy, purpose, isFreeText, isCritical, status, " +
                    "startEpochMs, endEpochMs, createdAtEpochMs, updatedAtEpochMs) VALUES " +
                    "('m3','Atorvastatin',NULL,'[]','40 mg','TABLET','1 tablet',NULL,NULL,NULL,0,0," +
                    "'ACTIVE',0,NULL,0,0)",
            )
        }

        // Apply MIGRATION_3_4 and validate the resulting schema matches Room's expectation.
        val v4 = migrationHelper.runMigrationsAndValidate(
            RegimenDatabaseFactory.DATABASE_NAME,
            4,
            true,
            RegimenDatabaseFactory.MIGRATION_3_4,
        )
        v4.use {
            // Pre-existing medication row survived.
            v4.query("SELECT COUNT(*) FROM medications", emptyArray<Any?>()).use { c ->
                assertTrue(c.moveToFirst())
                assertEquals(1, c.getInt(0))
            }
            // missWindowMinutes column exists and defaults to 60 for all pre-existing rows.
            v4.query(
                "SELECT missWindowMinutes FROM medications WHERE id = 'm3'",
                emptyArray<Any?>(),
            ).use { c ->
                assertTrue("Row must still exist after migration", c.moveToFirst())
                assertEquals(
                    "missWindowMinutes must default to 60 for pre-existing rows (no behavioral change)",
                    60,
                    c.getInt(0),
                )
            }
        }
    }
}
