package com.beryndil.pharos.data.regimen

import androidx.room.testing.MigrationTestHelper
import androidx.test.platform.app.InstrumentationRegistry
import org.junit.Assert.assertTrue
import org.junit.Rule
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.RobolectricTestRunner

/**
 * Migration test harness for [RegimenDatabase] (spec §3.5, Standards §5).
 *
 * At schema v1, there are no migrations to test. The harness validates that:
 * 1. The exported schema JSON was generated by KSP before tests run.
 * 2. [MigrationTestHelper.createDatabase] can create a v1 database from the schema JSON.
 * 3. All required tables exist in the v1 schema.
 *
 * When v2 is added (any future slice that adds/modifies a column), add a
 * testMigrateV1ToV2() test here with the corresponding migration SQL.
 *
 * Schema assets exposed to Robolectric via:
 *   sourceSets { named("test") { assets.srcDir("$projectDir/schemas") } }
 */
@RunWith(RobolectricTestRunner::class)
class MigrationHarnessTest {

    @get:Rule
    val migrationHelper: MigrationTestHelper = MigrationTestHelper(
        InstrumentationRegistry.getInstrumentation(),
        RegimenDatabase::class.java,
    )

    @Test
    fun createV1SchemaAndVerifyAllTables() {
        val db = migrationHelper.createDatabase(RegimenDatabaseFactory.DATABASE_NAME, 1)
        db.use {
            val tables = mutableSetOf<String>()
            db.query(
                "SELECT name FROM sqlite_master WHERE type='table'",
                emptyArray<Any?>(),
            ).use { cursor ->
                while (cursor.moveToNext()) tables.add(cursor.getString(0))
            }
            val requiredTables = listOf(
                "medications",
                "schedules",
                "schedule_phases",
                "dose_instances",
                "refill_records",
                "settings",
            )
            for (table in requiredTables) {
                assertTrue("Table '$table' must exist in v1 schema", tables.contains(table))
            }
        }
    }

    /** dose_instances must be queryable on an empty v1 database. */
    @Test
    fun v1DoseInstancesTableIsQueryable() {
        val db = migrationHelper.createDatabase(RegimenDatabaseFactory.DATABASE_NAME, 1)
        db.use {
            db.query(
                "SELECT id, state FROM dose_instances WHERE state='SCHEDULED'",
                emptyArray<Any?>(),
            ).use { cursor ->
                assertTrue(
                    "Query on empty dose_instances must return 0 rows",
                    !cursor.moveToFirst(),
                )
            }
        }
    }
}
