package com.beryndil.pharos.data.drugref.entity

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.Index
import androidx.room.PrimaryKey

/**
 * A drug concept from the RxNorm pipeline (table `drug_search`).
 *
 * Covers generics (IN/PIN/MIN), branded products (BN), and clinical drug forms (SCD/SBD/…).
 * The same RxCUI may appear more than once across different TTY rows, so [rxcui] is NOT the
 * primary key — Room uses an autogenerated surrogate key instead (DECISIONS.md G2b).
 *
 * [nameLower] = [name].lowercase() — stored for fast case-insensitive LIKE searches on the
 * `idx_name_lower` index without a full-table scan.
 */
@Entity(
    tableName = "drug_search",
    indices = [
        Index(value = ["name_lower"], name = "idx_name_lower"),
        Index(value = ["rxcui"], name = "idx_rxcui"),
    ],
)
data class DrugSearchEntity(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,

    /** RxNorm Concept Unique Identifier. NOT unique — same RxCUI can have multiple TTY rows. */
    val rxcui: String,

    /** Canonical drug name as returned by RxNorm. */
    val name: String,

    /** [name].lowercase() — used for case-insensitive LIKE prefix/contains searches. */
    @ColumnInfo(name = "name_lower") val nameLower: String,

    /**
     * RxNorm term type.
     * Common values: IN = ingredient, PIN = precise ingredient, MIN = multi-ingredient name,
     * BN = brand name, SCD = clinical drug, SBD = branded drug.
     */
    val tty: String,
)
